services:
  redis:
    image: "redis:latest"
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:latest
    container_name: minio-server
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
  go-video:
    build: .
    container_name: GO_Video
    restart: always
    depends_on:
      - redis
      - kafka
      - minio
    ports:
      - "8000:8000"